CREATE TABLE reports (
    filing_id          UUID                        NOT NULL PRIMARY KEY,
    status             VARCHAR(20)                 NOT NULL,
    overall_risk_level VARCHAR(20),
    total_findings     INT                         NOT NULL DEFAULT 0,
    rules_version      VARCHAR(32),
    generated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    failure_reason     VARCHAR(1000),
    CONSTRAINT ck_reports_status CHECK (status IN ('COMPLETED', 'FAILED'))
);

CREATE TABLE findings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filing_id    UUID          NOT NULL,
    category     VARCHAR(20)   NOT NULL,
    severity     VARCHAR(20)   NOT NULL,
    rule_id      VARCHAR(32)   NOT NULL,
    matched_text VARCHAR(500)  NOT NULL,
    excerpt      VARCHAR(1000) NOT NULL,
    position     INT           NOT NULL,
    CONSTRAINT fk_findings_report FOREIGN KEY (filing_id) REFERENCES reports (filing_id) ON DELETE CASCADE
);

CREATE INDEX ix_findings_filing_id ON findings (filing_id);

-- Idempotency: one row per consumed eventId.
CREATE TABLE processed_events (
    event_id     UUID                        NOT NULL PRIMARY KEY,
    processed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
